name: static.031130.xyz
on:
  workflow_dispatch:
  schedule:
    - cron: '44 4 4 * *'  # Choose a unique time so CA won't get too much pressure. 

env:
  domain: static.031130.xyz

jobs:
  issue-push:
    name: Issue && Push
    runs-on: ubuntu-latest
    steps:
    - name: Install acme.sh
      run: curl https://get.acme.sh | sh
    - name: Extract account files for acme.sh
      run: |
        echo "${{ secrets.ACME_SH_ACCOUNT_TAR }}" | base64 -d | tar -C ~/.acme.sh -xz
    - name: Issue Certificate
      run: |
        mkdir -p output
        ~/.acme.sh/acme.sh --issue --dns dns_cf --force -d ${{ env.domain }} --fullchain-file output/fullchain.pem --key-file output/key.pem
    - name: zip Certificate
      run: |
        zip -j output/${{ env.domain }}_$(date +%Y%m%d).zip output/fullchain.pem output/key.pem
    - name: Push Certificate
      run: |
        TG_BOT_TOKEN="${{ secrets.TG_BOT_TOKEN }}"
        TG_CHAT_ID="${{ secrets.TG_CHAT_ID }}"
        curl -s -X POST https://api.telegram.org/bot${TG_BOT_TOKEN}/sendDocument -F chat_id=${TG_CHAT_ID} -F document="@output/${{ env.domain }}_$(date +%Y%m%d).zip"
    - name: Deploy To Upyun
      uses: Menci/deploy-certificate-to-upyun@beta-v2
      with:
        subaccount-username: ${{ secrets.UPYUN_SUBACCOUNT_USERNAME }}
        subaccount-password: ${{ secrets.UPYUN_SUBACCOUNT_PASSWORD }}
        fullchain-file: output/fullchain.pem
        key-file: output/key.pem
        domains: |
          ${{ env.domain }}
        delete-unused-certificates: true
